### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by sunscreem** [timacdonald/kumulos-api#1]
Hi Tim,

I've just installed your package and successfully connected up to the kumulos api.

I've started to swap out some of the basic methods (create, delete) on my controllers, but I'm wondering how I'm going to deal with eloquent relationships. Have you solved that one?

Rob

**Comment by sunscreem** [comment]
I kind feel like I want to get all the basic CRUD operations wrapped up and hidden away so eloquent can continue to be used, albeit with "remote database" actually being kumlous.

**Comment by timacdonald** [comment]
Hey Rob,

This would be fantastic if possible. This package is (unfortunately) just a thin wrapper around the Kumulos HTTP API.

If you wanted to use it behind the scenes with Eloquent - Kumulos would have to offer a way to connect to the database directly - not via hitting HTTP endpoints as they do now. I personally don't really see them offering that functionality (I could be wrong).

You could probably hack into Laravel to try and get it working via the HTTP API - but I don't think it will ever be 100%.

**Comment by sunscreem** [comment]
Yeah - after reading that and having a think about it I think I'll just use your package to basically mirror my own database. I'll hook into the eloquent events for the CRUD stuff and try and keep the two in sync. 

I'll maybe pop back and let you know how it works out in the next week or two.

Out of interest - see the step where you do the binding in the AppServiceProvider, is there not a way to do that automatically? I've only build one basic laravel package myself so forgive me if that's a dumb question.

**Comment by timacdonald** [comment]
Not a dumb question at all. Over the weekend I'll try an put some time aside to create a version that will do this for you automatically!

**Comment by sunscreem** [comment]
What a gent. :)
