### ISSUE TITLE
My Implementation

### ISSUE THREAD

**Issue by sunscreem** [timacdonald/kumulos-api#2]
Hi Again,

https://gist.github.com/sunscreem/7a273f879c270eb21dd4b90149daeb74

Just thought I'd share a prototype of an implementation I've got working this afternoon. 

In a nutshell I'm using laravels model events to do a create, read or update with Kumulos using your wrapper. This keeps the kumulos database 'in sync' with my own one. I'm happy with this as its lets me continue to do all the usual stuff using laravel eloquent (including all the auth stuff) while syncing nicely with Kumulos.

It also keeps my models nice and clean since all this code it tucked away from the main app logic.

Thanks again for creating this package - saved me a LOT of time.

**Comment by timacdonald** [comment]
Hey - no problem, that is very cool that you got that going!

The only thing I'd say is it will slow down requests, but that might not be a huge concern to begin with. You could probably look at throwing the updates to the Kumulos API on a queue - that would be really cool. That way it would happen in the background and not during the request cycle while the user is waiting.

Apart from that - congrats on getting it working 👍  really glad it is helping.

**Comment by sunscreem** [comment]
Thank Tim. Glad you noticed that approach re slowing requests down.

I thought about this for quite a while. My main concern was how to prevent my laravel database going out-of-sync with kumulos.

In the case of this app that I'm building its vital that if a user updates some data, that its reflected immediately in Kumulos. So I decided to use laravels `creating`, `updating`, `deleting` methods, instead of `created`, `updated` and `deleted`, so that if anything goes wrong between my app and Kumulos then the change doesn't get committed to my database. 

In reality there no noticeable lag, it adds about 300-400ms to the round trip :)

**Comment by timacdonald** [comment]
yea, that is very nice approach for sure. super pumped it is working out well for ya!

**Comment by timacdonald** [comment]
I especially like seeing that the `normalized...` methods were handy for you. Makes much more sense t use those to me, not really sure why they went with custom error codes / messages.
